import { integer, text, boolean, pgTable, serial, timestamp, varchar, uniqueIndex } from 'drizzle-orm/pg-core';

// This file defines the structure of your database tables using the Drizzle ORM.

// To modify the database schema:
// 1. Update this file with your desired changes.
// 2. Generate a new migration by running: `npm run db:generate`

// The generated migration file will reflect your schema changes.
// It automatically run the command `db-server:file`, which apply the migration before Next.js starts in development mode,
// Alternatively, if your database is running, you can run `npm run db:migrate` and there is no need to restart the server.

// Need a database for production? Check out https://www.prisma.io/?via=nextjsboilerplate
// Tested and compatible with Next.js Boilerplate

export const counterSchema = pgTable('counter', {
  id: serial('id').primaryKey(),
  count: integer('count').default(0),
  updatedAt: timestamp('updated_at', { mode: 'date' })
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
});

export const userSchema = pgTable('user', {
  id: serial('id').primaryKey(),
  name: text('name'),
  email: text('email').notNull().unique(),
  // Nullable — Google OAuth users have no password; email/password users always have a hash.
  password: text('password'),
  role: varchar('role', { length: 20 }).default('user'),
  emailVerified: boolean('email_verified').default(false),
  emailOtp: text('email_otp'),
  otpExpiry: timestamp('otp_expiry'),
  otpPurpose: text('otp_purpose'),
  // IANA timezone name (e.g. 'America/New_York'). Used by the credit reset job
  // to reset daily credits at local midnight instead of UTC midnight.
  // Captured from the browser via Intl.DateTimeFormat().resolvedOptions().timeZone at signup.
  timezone: text('timezone').notNull().default('UTC'),
  // Google OAuth subject ID — set when the user signs in via Google for the first time.
  // Null for email/password accounts. Unique so each Google account maps to one user row.
  googleId: text('google_id').unique(),
  // Profile photo URL — stored as a path under /public/avatars/ or a CDN URL.
  // Null means the UI falls back to gradient-initials avatar.
  avatarUrl: text('avatar_url'),
  // TOTP 2FA — secret is a base32 string generated by otplib.
  // Null until the user goes through the 2FA setup flow in Settings.
  twoFactorSecret: text('two_factor_secret'),
  // Whether 2FA is currently active for this account.
  twoFactorEnabled: boolean('two_factor_enabled').notNull().default(false),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

export const refreshTokensSchema = pgTable('refresh_tokens', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull(),
  tokenHash: text('token_hash').notNull(),
  expiresAt: timestamp('expires_at', { mode: 'date' }).notNull(),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
});

export const jobTitleSchema = pgTable('job_title', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  description: text('description'),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
  //userId: uuid('user_id')                       // reference user UUID
});


export const companyIndustrySchema = pgTable('company_industry', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),               // e.g., "Software", "Finance"
  description: text('description'),           // optional description
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

export const technologySchema = pgTable('technology', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),               // e.g., "Software", "Finance"
  description: text('description'),           // optional description
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

export const skillSchema = pgTable('skill', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),               // e.g., "Software", "Finance"
  description: text('description'),           // optional description
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

export const educationSchema = pgTable('education', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),               // e.g., "Software", "Finance"
  description: text('description'),           // optional description
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

export const managementLevelSchema = pgTable('management_level', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),               // e.g., "Software", "Finance"
  description: text('description'),           // optional description
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

export const departmentSchema = pgTable('department', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),               // e.g., "Software", "Finance"
  description: text('description'),           // optional description
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

export const countrySchema = pgTable('country', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),                 // e.g., "United States"
  code: text('code').notNull().unique(),        // e.g., "US"
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

export const citySchema = pgTable('city', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),                 // City name, e.g., "New York"
  countryId: integer('country_id').references(() => countrySchema.id), // Reference to country,
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

// Company lookup table — normalised from lead_data.company_name
// The SQL migration that created this table also migrated existing data.
export const companySchema = pgTable('company', {
  id: serial('id').primaryKey(),
  companyName: text('company_name').notNull().unique(), // company name, must be unique
  description: text('description'),                    // optional description
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

export const companySizeSchema = pgTable('company_size', {
  id: serial('id').primaryKey(), 
  label: text('label').notNull(),             // e.g., "1-10 employees"
  minEmployees: text('min_employees'),        // optional: numeric range start
  maxEmployees: text('max_employees'),        // optional: numeric range end
  description: text('description'),           // optional description
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

export const leadDataSchema = pgTable('lead_data', {
  id: serial('id').primaryKey(),
  firstName: text('first_name'),
  lastName: text('last_name'),
  avatarUrl: text('avatar_url'),
  personalLinkedIn: text('personal_linkedin'),
  // Company / person website URL — shown as a clickable globe icon in the Reference column
  websiteUrl: text('website_url'),
  // company_name column was dropped; use companyId FK to the company table instead
  companyId: integer('company_id').references(() => companySchema.id),
  workEmail: text('work_email').unique(),
  personalEmail: text('personal_email').unique(),
  phone1: text('phone1').unique(),
  phone2: text('phone2').unique(),
  emailVerified: boolean('email_verified').default(false),
  jobTitleId: integer('job_title_id').references(() => jobTitleSchema.id),
  cityId: integer('city_id').references(() => citySchema.id),
  countryId: integer('country_id').references(() => countrySchema.id),
  educationId: integer('education_id').references(() => educationSchema.id),
  managementLevelId: integer('management_level_id').references(() => managementLevelSchema.id),
  departmentId: integer('department_id').references(() => departmentSchema.id),
  companySizeId: integer('company_size_id').references(() => companySizeSchema.id),
  companyIndustryId: integer('company_industry_id').references(() => companyIndustrySchema.id),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

// Many-to-many: a lead can have multiple technologies
export const leadTechnologySchema = pgTable('lead_technology', {
  id: serial('id').primaryKey(),
  leadId: integer('lead_id').references(() => leadDataSchema.id, { onDelete: 'cascade' }).notNull(),
  technologyId: integer('technology_id').references(() => technologySchema.id, { onDelete: 'cascade' }).notNull(),
});

// Many-to-many: a lead can have multiple skills
export const leadSkillSchema = pgTable('lead_skill', {
  id: serial('id').primaryKey(),
  leadId: integer('lead_id').references(() => leadDataSchema.id, { onDelete: 'cascade' }).notNull(),
  skillId: integer('skill_id').references(() => skillSchema.id, { onDelete: 'cascade' }).notNull(),
});

// Tracks which contacts a user has revealed (no re-charge on repeat view)
export const revealedContactSchema = pgTable('revealed_contact', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull(),
  personId: integer('person_id').references(() => leadDataSchema.id, { onDelete: 'cascade' }).notNull(),
  workEmail: text('work_email'),
  personalEmail: text('personal_email'),
  phone1: text('phone1'),
  phone2: text('phone2'),
  // Email verification status from an external verification service (or null = unverified).
  // 'deliverable' → green check, 'risky' → yellow warning, 'undeliverable' → red cross
  workEmailStatus: varchar('work_email_status', { length: 20 }),      // deliverable | risky | undeliverable | null
  personalEmailStatus: varchar('personal_email_status', { length: 20 }), // deliverable | risky | undeliverable | null
  // When true, 1 credit was automatically refunded because the email was undeliverable.
  // Shown as "+1 ⚡ Refunded" badge in the Reveal History UI.
  creditRefunded: boolean('credit_refunded').notNull().default(false),
  revealedAt: timestamp('revealed_at', { mode: 'date' }).defaultNow().notNull(),
});

// Daily credit balance per user (20 credits/day for free users)
export const userCreditSchema = pgTable('user_credit', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull().unique(),
  remaining: integer('remaining').notNull().default(20),
  dailyLimit: integer('daily_limit').notNull().default(20),
  resetsAt: timestamp('resets_at', { mode: 'date' }).notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

// Named lists that users create to organise leads
export const userListSchema = pgTable('user_list', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull(),
  listName: text('list_name').notNull(),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

// Join table: which leads belong to which list
export const listLeadSchema = pgTable('list_lead', {
  id: serial('id').primaryKey(),
  listId: integer('list_id').references(() => userListSchema.id, { onDelete: 'cascade' }).notNull(),
  leadId: integer('lead_id').references(() => leadDataSchema.id, { onDelete: 'cascade' }).notNull(),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
});

// Saved filter sets ("Save Filters" in the sidebar)
export const savedSearchSchema = pgTable('saved_search', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull(),
  name: text('name').notNull(),
  searchJson: text('search_json').notNull(), // JSON-serialised LeadsSearchPayload
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

// Stripe subscription per user (one row per user, upserted on checkout)
export const userSubscriptionSchema = pgTable('user_subscription', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull().unique(),
  plan: varchar('plan', { length: 20 }).notNull().default('free'), // free | unlimited
  stripeCustomerId: text('stripe_customer_id').unique(),
  stripeSubscriptionId: text('stripe_subscription_id').unique(),
  status: varchar('status', { length: 20 }).notNull().default('active'), // active | canceled | past_due | trialing
  currentPeriodStart: timestamp('current_period_start', { mode: 'date' }),
  currentPeriodEnd: timestamp('current_period_end', { mode: 'date' }),
  cancelAtPeriodEnd: boolean('cancel_at_period_end').notNull().default(false),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

// CSV files uploaded by users (for include/exclude filtering by email, LinkedIn URL, company name, company website)
export const uploadedFileSchema = pgTable('uploaded_file', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull(),
  uploadName: text('upload_name').notNull(),
  filename: text('filename').notNull(),
  filePath: text('file_path').notNull(),
  firstRowIsHeader: boolean('first_row_is_header').notNull().default(true),
  emailColumn: integer('email_column'),             // 0-based CSV column index mapped to Email
  linkedInColumn: integer('linkedin_column'),       // 0-based CSV column index mapped to LinkedIn URL
  companyNameColumn: integer('company_name_column'), // 0-based CSV column index mapped to Company Name
  companyWebsiteColumn: integer('company_website_column'), // 0-based CSV column index mapped to Company Website
  rowCount: integer('row_count').notNull().default(0),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
});

// User-favourited leads with colour-coded priority tags.
// One row per (user, lead, tag) combination — a user can favourite the same lead
// multiple times with different tags (though the UI currently picks one per lead).
export const userFavoriteSchema = pgTable('user_favorite', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull(),
  leadId: integer('lead_id').references(() => leadDataSchema.id, { onDelete: 'cascade' }).notNull(),
  // Human-readable tag name shown in the UI, e.g. "High Priority", "Follow Up"
  tagName: text('tag_name').notNull().default(''),
  // Hex colour for the tag badge, e.g. "#ef4444" (red) or "#3b82f6" (blue)
  tagColor: text('tag_color').notNull().default('#6366f1'),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
});

// ── Team Management ───────────────────────────────────────────────────────────
// A "team" is owned by one user (the owner / admin who invited others).
// Each invited member gets a row in team_member; pending invites have no userId yet.

/**
 * Represents an invited or active team member under an owner's account.
 * - ownerId: the user who created / manages the team
 * - userId: set when the invitee accepts the invite (nullable until then)
 * - role: 'admin' | 'member' | 'viewer'
 * - creditQuota: daily credit limit assigned to this member (0 = no limit)
 * - creditsUsed: credits consumed today by this member
 * - status: 'pending' | 'active' | 'inactive'
 * - lowCreditAlert: when true the owner gets notified if this member runs low
 * - inviteToken: random UUID token in invite link (null after acceptance)
 */
export const teamMemberSchema = pgTable('team_member', {
  id: serial('id').primaryKey(),
  // The workspace owner who sent the invite
  ownerId: integer('owner_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull(),
  // Set after the invite is accepted — null while still pending
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'set null' }),
  // Email address the invite was sent to
  invitedEmail: text('invited_email').notNull(),
  // Display name — populated when invite is accepted from user.name
  name: text('name'),
  // Role within the team
  role: varchar('role', { length: 20 }).notNull().default('member'), // admin | member | viewer
  // Daily credit cap for this member; 0 means no cap applied
  creditQuota: integer('credit_quota').notNull().default(0),
  // Credits this member has consumed today (reset nightly with the credit job)
  creditsUsed: integer('credits_used').notNull().default(0),
  // Lifecycle state of the membership
  status: varchar('status', { length: 20 }).notNull().default('pending'), // pending | active | inactive
  // Owner opt-in: receive alert when this member's remaining credits drop below 20%
  lowCreditAlert: boolean('low_credit_alert').notNull().default(false),
  // One-time invite token embedded in the invite URL — cleared after acceptance
  inviteToken: text('invite_token').unique(),
  invitedAt: timestamp('invited_at', { mode: 'date' }).defaultNow().notNull(),
  joinedAt: timestamp('joined_at', { mode: 'date' }),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

// ── Feedback & Suggestions ────────────────────────────────────────────────────
// Users submit bug reports, feature requests, or general messages.
// Other users can upvote submissions — one upvote row per (voter, feedback) pair.
// Admins set the status to drive the "Wall of Love & Ideas" feed.

/**
 * A piece of feedback submitted by any authenticated user.
 * - category: 'bug' | 'feature' | 'general'
 * - mood: 1–5 emoji score (1=😡 … 5=😍) — optional, captured before the form
 * - status: 'open' | 'investigating' | 'planned' | 'in-progress' | 'completed' | 'declined'
 * - votes: denormalised upvote count for fast sorting (incremented by the vote route)
 */
export const feedbackSchema = pgTable('feedback', {
  id: serial('id').primaryKey(),
  // Author — kept so the author can see their own submissions
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull(),
  // Feedback category — determines icon and colour in the UI
  category: varchar('category', { length: 20 }).notNull().default('general'), // bug | feature | general
  // Mood score captured via the emoji bar before the form opens (null if skipped)
  mood: integer('mood'),                     // 1–5 (1=😡 2=🙁 3=😐 4=🙂 5=😍)
  // Short summary shown in the community feed
  title: text('title').notNull(),
  // Full description / reproduction steps
  message: text('message').notNull().default(''),
  // Lifecycle status set by an admin
  status: varchar('status', { length: 20 }).notNull().default('open'),
  // Denormalised upvote count — incremented atomically by the vote route
  votes: integer('votes').notNull().default(0),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

/**
 * Tracks which users have upvoted which feedback items.
 * Prevents double-voting and lets the UI show whether the current user has voted.
 */
export const feedbackVoteSchema = pgTable('feedback_vote', {
  id: serial('id').primaryKey(),
  // The feedback item being upvoted
  feedbackId: integer('feedback_id').references(() => feedbackSchema.id, { onDelete: 'cascade' }).notNull(),
  // The voter
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull(),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
});

// ── Release Reactions ─────────────────────────────────────────────────────────
// Stores emoji reactions left by users on What's New release cards.
// One row per (userId, version, emoji) — unique constraint prevents duplicates.
// A separate denormalised count table is avoided; counts are computed via aggregation.

/**
 * A single emoji reaction by a user on a release version.
 * Toggling the same emoji again deletes the row (toggle model).
 * Supported emoji: '❤️' | '🚀' | '👍'
 */
export const releaseReactionSchema = pgTable('release_reaction', {
  id: serial('id').primaryKey(),
  // The user who reacted
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull(),
  // Semver string identifying the release (e.g. "1.4.0")
  version: varchar('version', { length: 20 }).notNull(),
  // The emoji the user chose — constrained to the 3 allowed values at the app layer
  emoji: varchar('emoji', { length: 10 }).notNull(),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
});

// ── User Settings ─────────────────────────────────────────────────────────────
// One row per user. Created on demand (upserted) when the user first saves settings.
// Stores UI preferences, notification thresholds, and export column configuration.

/**
 * Persisted user preferences.
 * - theme: 'light' | 'dark' | 'auto'  — applied as a CSS class on <html>
 * - exportColumnsJson: JSON array of CSV column keys in the user-defined order
 * - creditAlertEnabled: send an email when credits drop below creditAlertThreshold
 * - creditAlertThreshold: integer credit value at which the alert fires
 */
export const userSettingsSchema = pgTable('user_settings', {
  id: serial('id').primaryKey(),
  // One settings row per user
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull().unique(),
  // UI colour scheme — 'auto' honours the OS prefers-color-scheme media query
  theme: varchar('theme', { length: 10 }).notNull().default('auto'), // light | dark | auto
  // Ordered JSON array of export column keys, e.g. ["firstName","lastName","workEmail"]
  exportColumnsJson: text('export_columns_json').notNull().default('[]'),
  // Notifications — low-credit email alert
  creditAlertEnabled: boolean('credit_alert_enabled').notNull().default(false),
  creditAlertThreshold: integer('credit_alert_threshold').notNull().default(5),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

// Background export jobs (CSV downloads)
export const exportJobSchema = pgTable('export_job', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull(),
  status: varchar('status', { length: 20 }).notNull().default('pending'), // pending | processing | completed | failed
  downloadUrl: text('download_url'),
  error: text('error'),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

// ── User Webhooks ─────────────────────────────────────────────────────────────
// Each user can register multiple webhook endpoints.
// When a lead.revealed or lead.exported event fires, all active webhooks for
// that user receive an HTTP POST with the event payload.

export const userWebhookSchema = pgTable('user_webhook', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull(),
  // Human-friendly name so the user can identify the endpoint (e.g. "Zapier lead sync")
  name: text('name').notNull().default(''),
  // The HTTP endpoint that receives the POST payload
  url: text('url').notNull(),
  // Optional secret sent as X-WarpLeads-Secret header for signature verification
  secret: text('secret'),
  // Comma-separated event list, e.g. "lead.revealed,lead.exported"
  events: text('events').notNull().default('lead.revealed'),
  // Soft on/off toggle without deleting the row
  active: boolean('active').notNull().default(true),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
});

// ── User Integrations (OAuth) ─────────────────────────────────────────────────
// One row per connected OAuth integration per user.
// provider: 'hubspot' | 'salesforce' | 'pipedrive' | 'zoho' | 'googlesheets'

export const userIntegrationSchema = pgTable('user_integration', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull(),
  // Which third-party tool this row represents
  provider: varchar('provider', { length: 30 }).notNull(),
  // OAuth access token (encrypted at rest in production — stored plain for MVP)
  accessToken: text('access_token').notNull(),
  // OAuth refresh token (may be null for providers that don't issue one)
  refreshToken: text('refresh_token'),
  // When the access token expires (null = non-expiring)
  expiresAt: timestamp('expires_at', { mode: 'date' }),
  // JSON blob for provider-specific metadata (e.g. portal ID, instance URL)
  metadata: text('metadata').notNull().default('{}'),
  // JSON blob for user-saved sync settings (e.g. { syncMode: 'on_reveal', pipeline: 'New Leads' })
  settings: text('settings').notNull().default('{}'),
  connectedAt: timestamp('connected_at', { mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).defaultNow(),
}, (t) => [
  // Unique constraint: each provider can only be connected once per user
  uniqueIndex('user_integration_user_provider_idx').on(t.userId, t.provider),
]);

// ── Integration Notify Me ─────────────────────────────────────────────────────
// Tracks which users want to be notified when a "coming soon" integration launches.
// Unique on (userId, provider) so duplicate clicks just resolve to the same row.

export const integrationNotifySchema = pgTable('integration_notify', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').references(() => userSchema.id, { onDelete: 'cascade' }).notNull(),
  // Integration identifier (e.g. 'salesforce', 'slack', 'gmail')
  provider: varchar('provider', { length: 30 }).notNull(),
  createdAt: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
}, (t) => [
  // Unique constraint: one notify-me row per (user, provider) pair
  uniqueIndex('integration_notify_user_provider_idx').on(t.userId, t.provider),
]);